### ISSUE TITLE
[Suggestion] Apply the patch as a PR on RN core

### ISSUE THREAD

**Issue by SaeedZhiany** [ifsnow/react-native-networking-patch#5]
First of all, Thanks for this library. I'm not starting using it yet but it seems an amazing improvement on the React-Native Network module.

I'm wondering why you don't try to apply this patch on react-native repository as a PR? so the improvements can be accessible out of the box on the core Network module.

**Comment by ifsnow** [comment]
@SaeedZhiany Thanks for your suggestion. This work has already been PR(https://github.com/facebook/react-native/pull/28959) in the RN core. 

I think that it's difficult to apply because the RN core has to take care of a lot of cases and also consider compatibility with the previous version. I fully understand their decision. :)

**Comment by SaeedZhiany** [comment]
Ah, I see now, I hope you manage to get the PR merged.

Thanks again, I'm closing this thread.
